services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      db:
        condition: service_healthy  # Wait for db to be healthy
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: react_frontend
    ports:
      - "3000:80"
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_DATABASE: chatbot_db
      MYSQL_USER: chatbot_user
      MYSQL_PASSWORD: temp_password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:  # Health check for the database
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s  # Check every 10 seconds
      timeout: 5s    # Time out after 5 seconds
      retries: 5      # Retry 5 times before marking as unhealthy

volumes:
  db_data:

networks:
  app-network:
